### ISSUE TITLE
oauth token is not picked up from ~/.gitconfig_local file

### ISSUE THREAD

**Issue by lislon** [defunkt/gist.el#95]
I want to use 2 separete gitconfig files (version control and local), but gist doesn't see my oauth token file when it's located in included file.

I have the following `~/.gitconfig` file:
```
[include]
  path = ~/.gitconfig_local
```
And my `~/.gitconfig_local`:
```
[github]
  oauth-token = my-long-token-here
```

I found out there is option `--includes` for `git config` command, which lookup values in includes too. 
```
git config --global github.oauth-token              # doesn't work
git config --global --includes github.oauth-token   # works
```

Can you fix this pls?

**Comment by sigma** [comment]
I'm puzzled because 
- that's pretty much how my own setup looks like
- the code in `gh.el` doesn't use the `--global` flag (which is the one disabling includes) for reading, only for writing. See https://github.com/sigma/gh.el/blob/master/gh-common.el#L57..L62

So it seems to me that if you make sure you have the right (upstream) version of `gh.el` installed, it should just work. Please let me know if I'm missing something
